### ISSUE TITLE
[QUESTION] How to pass in matchers of type IMatcher<IEnumerable<T>> as an argument to my method?

### ISSUE THREAD

**Issue by basdijkstra** [nhamcrest/NHamcrest#16]
So, this is maybe more of a generic C# programming question than an NHamcrest question, but here goes anyway.

What I'm trying to achieve is writing a method that takes a matcher of type `IMatcher<IEnumerable<T>>` as an argument. Here's my current method signature:
```csharp
public VerifiableResponse Body<T>(string jsonPath, IMatcher<IEnumerable<T>> matcher) {}
```

However, trying to call it using
```csharp
.Body("$.Places.Name", NHamcrest.Has.Item("San Francisco"))
```
results in a compilation error.

It works for matchers of type `IMatcher<T>`, where my method signature is
```csharp
public VerifiableResponse Body<T>(string jsonPath, IMatcher<T> matcher)
```

As you can tell, I'm not an expert on generics, but how would I need to modify my method signature to make this work?

**Comment by CaptnCodr** [comment]
Hey @basdijkstra,
`Has.Item` takes an `IMatcher<T>`, I guess your call needs an `Is.EqualTo`, so:
```csharp
.Body("$.Places.Name", NHamcrest.Has.Item(Is.EqualTo("San Francisco")))
```
Does this help for you? 🙂

**Comment by basdijkstra** [comment]
That definitely helps! I'm so used to the Java Hamcrest syntax I assumed I did it right... Thanks so much.
