### ISSUE TITLE
2 feature requests (1: `Assert.That` custom description, 2: shortcut `Is = equalTo`)

### ISSUE THREAD

**Issue by DatStorm** [nhamcrest/NHamcrest#18]
Hey.

Thanks for a great lib. I have 2 ideas for improvements to this lib:

1: Make the `Assert.That(...)` take a third argument with a custom description. This would make failing test easier to debug in pipelines.

2: Make a shortcut friendly version of `EqualTo` named `Is` (so new name for the class) such that instead of `Assert.That(x, Is.EqualTo(y))` it becomes `Assert.That(x, Is(y))`

It is already implemented here in Java: https://hamcrest.org/JavaHamcrest/javadoc/1.3/org/hamcrest/core/Is.html#is(T)

**Comment by CaptnCodr** [comment]
Hey @DatStorm, 
I fiddled around and gathered some information, as it is implemented in java, it couldn't be like this in C#. 
But I have a good implementation according to your **2nd feature request**, would be the following good for you?
```csharp
using Xunit;
using static NHamcrest.Extensions.IsExtensions; // <- import this

public class Tests 
{
    [Fact]
    public void Match_if_Is_true()
    {
        Assert.That(true, Is(true)); // <- use Is()
    }
}
```
To **feature request 1**:
I assume that you're using Xunit? The NUnit extension has this already, I would implement this for Xunit too.

**Comment by DatStorm** [comment]
2nd: Yes that would not be a problem that looks great.
1st: Great looking forward to the update to the lib.

Thank you for all the great work! :100:

**Comment by CaptnCodr** [comment]
This has been done in v3.2.0.

**Comment by DatStorm** [comment]
Why can it not be updated over nuget?

**Comment by CaptnCodr** [comment]
I and @grahamrhay are currently not the owner of that package. I try to find a way to change this.

**Comment by DatStorm** [comment]
@Lashas83

**Comment by DatStorm** [comment]
@Lashas83 can you make @CaptnCodr the co owner of the package 😊

**Comment by CaptnCodr** [comment]
Ping @Lashas83

**Comment by CaptnCodr** [comment]
@Lashas83 Yea, just add me as owner for `NHamcrest.Xunit` on nuget.org, then I'll update that package. 
My username there is "CaptnCodr", too. 

Drop a message, when you need help. 😊

**Comment by Lashas83** [comment]
@CaptnCodr I see that you are already added as an owner. Maybe @grahamrhay has added you there already.

**Comment by DatStorm** [comment]
Great news!
