### ISSUE TITLE
Xunit .That matches and Generics

### ISSUE THREAD

**Issue by ghost** [nhamcrest/NHamcrest#4]
When using 

```
InterfaceType1 sut = new T2(); // T2 implements InterfaceType1;
Assert.That(sut,Is.InstanceOf<T2>());
```

`.That<T>(T object, Matcher<T> matcher)` doesnt compile on the above but seems like a reasonable thing to do.

Workaround:

```
Assert.That(sut,Is.InstanceOf(typeof(T2))));
```

**Comment by CaptnCodr** [comment]
Closed because of no relevance anymore.
