### ISSUE TITLE
Non-generic versions of collection matchers

### ISSUE THREAD

**Issue by StuporHero** [nhamcrest/NHamcrest#7]
I'd like to be able to use `Has.Items` with a non-generic `IEnumerable` so I can ensure complete code coverage of collection classes which require an implementation of `IEnumerable.GetEnumerator`.

**Comment by CaptnCodr** [comment]
Hey @StuporHero, 
do you have still the need for this feature? Do you have a workaround for this or something else?
In the first sight I would use `IEnumerable<object>` or like this to solve this.

**Comment by StuporHero** [comment]
I don't remember opening this, so I can't even remember my use case. It doesn't matter to me now if this gets implemented.

**Comment by CaptnCodr** [comment]
Alright, thanks for your fast response.
